---
title: "PK summary table"
date: "Compiled on `r format(Sys.time(), '%B %d, %Y')`"
output: word_document
---

```{r set-options, echo=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
                      dpi = 300, 
                      fig.width = 6, 
                      fig.height = 5)

```

```{r}

flextable_simcyp <- function(DF){
    
    DF %>% flextable::flextable() %>% 
        flextable::bold(part = "header") %>%
        flextable::bold(j = 1, part = "body") %>% 
        flextable::align(align = "center", part = "header") %>%
        flextable::border_remove() %>% 
        flextable::border_inner_v(part = "all", 
                                  border = officer::fp_border(width = 0.5)) %>% 
        flextable::border_outer(border = officer::fp_border(width = 0.5)) %>% 
        flextable::set_table_properties(width = 1, layout = "autofit")
    
}

```

```{r}

if("File" %in% names(MyPKResults)){
    MyPKResults <- MyPKResults %>% 
        select(!matches("File"), File)
}

flextable_simcyp(MyPKResults)

```




