#' Graph for checking accumulation over multiple doses -- UNDER CONSTRUCTION
#'
#' UNDER CONSTRUCTION -- DoseNum must be complete. Haven't done much to make
#' this "nice" yet. Just using it for a project I'm working on and thought I'd
#' add it. -LSh
#'
#' @param t0 start time for compound being plotted
#' @param timepoint Time point to plot. Options are:
#'   \describe{\item{"tmin"}{whenever the minimum concentration occurred for
#'   that dosing interval, which may not be the last time point}
#'   \item{"tmax"}{whenever the maximum observed concentration for that dose
#'   number occurred} \item{"t0"}{the first time point available for that dose}
#'   \item{"tlast"}{the last time point available for that dose}}
#' @param mark_dosing set how to mark dosing intervals on the graph as "none"
#'   (default) to have no marks for the dosing interavls or a combination of a
#'   named color in R and a named linetype, e.g., "red dotted" or "blue dashed".
#' @param diff_cutoff what percent difference cutoff would you like to color the
#'   points by? The default is for points with less than a 5\% difference from
#'   the previous point to be blue and points with a larger percent difference
#'   to be red.
#' @param sim_obs_dataframe the input concentration-time data generated by
#'   running the function \code{\link{extractConcTime}} or, if you'd also like
#'   to see an overlay of the substrate with or without any inhibitors, by
#'   running \code{\link{extractConcTime_mult}}. This function assumes only one
#'   tissue is included, so you'll get graph artifacts if that's not the case.
#' @param mean_type the mean type to use since this function only displays
#'   summary data; defaults to the arithmetic mean
#' @param accum_compoundID the compound ID to monitor for accumulation. Defaults
#'   to "inhibitor 1". The time point requested will be shown as points and will
#'   be colored by percent difference from the previous point.
#' @param overlay_compoundID the compound ID to overlay the complete
#'   concentration-time data for. Defaults to "substrate"; use "none" for no
#'   overlaid plot. This was designed for the following scenario: Monitor
#'   Ctrough for an inhibitor to make sure that it's at steady state, plot that
#'   as points, and then plot the concentration-time profile of a substrate over
#'   that to make sure that the inhibitor is present the whole time you're
#'   monitoring the substrate. 
#'
#' @return
#' @export
#'
#' @examples
#'
#' CT <- extractConcTime()
#'
#' 
check_accumulation <- function(sim_obs_dataframe,
                               accum_compoundID = "inhibitor 1", 
                               overlay_compoundID = "substrate",
                               t0 = 0,
                               timepoint = "tlast",
                               mark_dosing = "none",
                               diff_cutoff = 0.05,
                               mean_type = "arithmetic"){
    
    MyMeanType <- sim_obs_dataframe %>%
        filter(CompoundID == accum_compoundID & 
                   Trial %in% c("geomean", "mean", "median")) %>% 
        pull(Trial) %>% unique() %>% 
        factor(levels = c("mean", "geomean", "median")) %>% 
        sort()
    
    if(switch(mean_type, "arithmetic" = "mean", "geometric" = "geomean",
              "median" = "median") %in% sim_obs_dataframe$Trial == FALSE){
        
        warning(paste0("You requested the ", 
                       switch(mean_type, "arithmetic" = "arithmetic means",
                              "geometric" = "geometric means", 
                              "median" = "medians"), 
                       ", but those are not included in your data. Instead, the ",
                       ifelse(MyMeanType[1] == "mean", 
                              "arithmetic mean", MyMeanType[1]),
                       "s will be used."))
        MyMeanType <- MyMeanType[1] %>% as.character()
        
    } else {
        MyMeanType <- switch(mean_type, "arithmetic" = "mean", "geometric" = "geomean",
                             "median" = "median")
    }
    
    SScheck <- sim_obs_dataframe %>% 
        filter(Trial == MyMeanType & CompoundID == accum_compoundID) %>%  
        group_by(DoseNum, Inhibitor) %>% 
        # switch doesn't seem to work with summarize. Calculating each value.
        summarize(t0 = min(Time),
                  tlast = max(Time),
                  tmin = Time[which.min(Conc)],
                  tmax = Time[which.max(Conc)], 
                  Cmin = min(Conc), 
                  Cmax = max(Conc), 
                  C0 = Conc[which.min(Time)], 
                  Clast = Conc[which.max(Time)]) %>% 
        ungroup() %>% 
        mutate(Conc = switch(timepoint, 
                             "tmin" = Cmin, 
                             "tmax" = Cmax, 
                             "t0" = C0, 
                             "tlast" = Clast), 
               Time = switch(timepoint, 
                             "tmin" = tmin, 
                             "tmax" = tmax,
                             "t0" = t0, 
                             "tlast" = tlast)) %>% 
        mutate(PercDiff = c(NA, diff(Conc, lag = 1))/Conc, 
               DiffCriterion = abs(PercDiff) < diff_cutoff,
               DiffCriterion = ifelse(is.na(DiffCriterion), FALSE, DiffCriterion))
    
    LineAES <- str_split(mark_dosing, pattern = " ")[[1]]
    
    G <- ggplot(SScheck, aes(x = Time, y = Conc, color = DiffCriterion))
    
    if(mark_dosing != "none"){
        G <- G + 
            geom_vline(xintercept = SScheck$t0, 
                       color = LineAES[1], linetype = LineAES[2])
    }
    
    G <- G +
        geom_point(size = 1) + 
        labs(color = paste0("Difference from previous point < ", 100*diff_cutoff, "%")) +
        xlab("Time (h)") +
        ylab(paste(timepoint, "(ng/mL)"))  +
        scale_color_brewer(palette = "Set1") +
        theme(panel.background = element_rect(fill="white", color=NA),
              legend.key = element_rect(fill = "white"),
              axis.ticks = element_line(color = "black"),
              axis.text = element_text(color = "black"),
              axis.title = element_text(color = "black", face = "bold"),
              axis.line.x.bottom = element_line(color = "black"),
              axis.line.y.left = element_line(color = "black"))
    
    
    if(overlay_compoundID != "none"){
        
        sim_obs_dataframe <- sim_obs_dataframe %>%
            mutate(Inhibitor = ifelse(is.na(Inhibitor), "none", Inhibitor))
        
        MyEffector <- unique(sim_obs_dataframe$Inhibitor[sim_obs_dataframe$Inhibitor != "none"])
        
        if(length(MyEffector) > 0){
            sim_obs_dataframe <- sim_obs_dataframe %>%
                mutate(Inhibitor = factor(Inhibitor, levels = c("none", MyEffector)))
        }
        
        OverlayCT <- sim_obs_dataframe %>% 
            filter(Trial == MyMeanType & CompoundID == overlay_compoundID) 
        
        if(length(MyEffector) > 0){
            G <- G + 
                geom_line(data = OverlayCT, 
                          aes(x = Time, y = Conc, linetype = Inhibitor), 
                          inherit.aes = F) +
                scale_linetype_manual(values = c("solid", "dashed"))
        } else {
            
            G <- G + 
                geom_line(data = OverlayCT, 
                          aes(x = Time, y = Conc), inherit.aes = F)
        }
        
        G <- G +
            # add somethign here for alpha for legend.
            scale_y_continuous(limits = c(0, max(c(OverlayCT$Conc, 
                                                   SScheck$Conc)))) 
        
    } else {
        G <- G + 
            scale_y_continuous(limits = c(0, max(SScheck$Conc)))
        
    }
    
    # Add legend item saying that points are for accum_compoundID and lines are
    # for overlay_compoundID.
    
    return(G)
    
}


