#' Concentration-time plots of the full time range, first dose, and last dose
#'
#' Conveniently group three concentration-time plots of multiple-dose regimen
#' data together: \enumerate{\item{the full time range across the top,}
#' \item{the first dose in the lower left quadrant, and}  \item{the last dose in
#' the lower right quadrant.}} This uses either \code{\link{ct_plot}} or
#' \code{\link{ct_plot_overlay}} behind the scenes to make the graphs, so most
#' of the options available for those functions will work here.
#'
#' @param ct_dataframe the input concentration-time data generated by running
#'   either the function \code{\link{extractConcTime}} or the function
#'   \code{\link{extractConcTime_mult}}
#' @param overlay TRUE or FALSE for whether to make overlaid graphs, i.e.,
#'   whether to use \code{\link{ct_plot_overlay}} (TRUE) or use
#'   \code{\link{ct_plot}} (FALSE) to generate the graphs
#' @param save_graph optionally save the output graph by supplying a file name
#'   in quotes here, e.g., "My conc time graph.png" or "My conc time
#'   graph.docx". If you leave off ".png" or ".docx" from the file name, it will
#'   be saved as a png file, but if you specify a different graphical file
#'   extension, it will be saved as that file format. Acceptable graphical file
#'   extensions are "eps", "ps", "jpeg", "jpg", "tiff", "png", "bmp", or "svg".
#'   Leaving this as NA means the file will not be saved to disk.
#'   \strong{WARNING:} SAVING TO WORD DOES NOT WORK ON SHAREPOINT OR THE LARGE
#'   FILE STORE. This is a Microsoft permissions issue, not an R issue. If you
#'   temporarily change your working directory to a local folder, it will work
#'   fine and you can copy those files later back to SharePoint or the Large
#'   File Store. We wish we had a better solution for this!
#' @param fig_height figure height in inches; default is 6
#' @param fig_width figure width in inches; default is 5
#' @param ... arguments that pass through to \code{\link{ct_plot}} or
#'   \code{\link{ct_plot_overlay}}
#'
#' @return
#' @export
#'
#' @examples
#'
#' data(LMVct)
#' ct_plot3(ct_dataframe = LMVct, linear_or_log = "log")
#'
#' data(MDZ_Keto)
#' ct_plot3(ct_dataframe = MDZ_Keto, overlay = TRUE, colorBy_column = CompoundID)
#' 

ct_plot3 <- function(ct_dataframe, 
                     overlay = FALSE, 
                     save_graph = NA,
                     fig_height = 6,
                     fig_width = 5,
                     ...){
    
    if(length(sort(unique(ct_dataframe$DoseNum))) == 1){
        stop("ct_plot3 is only for multiple-dose scenarios, but these data appear to be for only one dose.")
    }
    
    if(hasArg("time_range")){
        stop("You cannot supply anything for 'time_range' here because ct_plot3 needs to set the time range automatically. Please remove 'time_range' from your arguments.")
    }
    
    if(overlay){
        
        A <- ct_plot_overlay(ct_dataframe = ct_dataframe,
                             time_range = NA,
                             ..., # comment this for development
                             save_graph = NA) +
            ggtitle("Full time range")
        
        # Suppressing messages and warnings after the 1st set.
        suppressWarnings(suppressMessages(
            B <- ct_plot_overlay(ct_dataframe = ct_dataframe,
                                 time_range = "first dose",
                                 ..., # comment this for development
                                 save_graph = NA) +
                ggtitle("First dose")))
        
        suppressWarnings(suppressMessages(
            C <- ct_plot_overlay(ct_dataframe = ct_dataframe,
                                 time_range = "last dose", 
                                 ..., # comment this for development
                                 save_graph = NA) +
                ggtitle("Last dose")))
        
        Out <- ggpubr::ggarrange(A, ggpubr::ggarrange(B, C, legend = "none"), 
                                 nrow = 2, common.legend = TRUE, legend = "bottom")
        
    } else {
        
        if(hasArg("colorBy_column") | hasArg("facet1_column") |
           hasArg("facet2_column")){
            stop("It looks like you wanted to use 'ct_plot_overlay' with this function to create graphs of overlaid concentration-time data, but you have specified 'overlay = FALSE' (or left it as the default). Please change 'overlay' to TRUE and try again.")
        }
        
        A <- ct_plot(ct_dataframe = ct_dataframe,
                     ..., # comment this for development
                     time_range = NA, 
                     save_graph = NA) +
            ggtitle("Full time range")
        
        suppressWarnings(suppressMessages(
            B <- ct_plot(ct_dataframe = ct_dataframe,
                         ..., # comment this for development
                         time_range = "first dose", 
                         save_graph = NA) +
                ggtitle("First dose")))
        
        suppressWarnings(suppressMessages(
            C <- ct_plot(ct_dataframe = ct_dataframe,
                         ..., # comment this for development
                         time_range = "last dose", 
                         save_graph = NA) +
                ggtitle("Last dose")))
        
        Out <- ggpubr::ggarrange(A, ggpubr::ggarrange(B, C, legend = "none"), 
                                 nrow = 2, common.legend = TRUE, legend = "bottom")
    }
    
    if(complete.cases(save_graph)){
        FileName <- save_graph
        if(str_detect(FileName, "\\.")){
            # Making sure they've got a good extension
            Ext <- sub("\\.", "", str_extract(FileName, "\\..*"))
            FileName <- sub(paste0(".", Ext), "", FileName)
            Ext <- ifelse(Ext %in% c("eps", "ps", "jpeg", "tiff",
                                     "png", "bmp", "svg", "jpg", "docx"), 
                          Ext, "png")
            FileName <- paste0(FileName, ".", Ext)
        } else {
            FileName <- paste0(FileName, ".png")
            Ext <- "png"
        }
        
        if(Ext == "docx"){
            # This is when they want a Word file as output
            OutPath <- dirname(FileName)
            
            if(OutPath == "."){
                OutPath <- getwd()
            }
            
            # All the \\\\ are necessary b/c \ is an escape character, and often
            # the SharePoint and Large File Store directory paths start with
            # \\\\.
            if(str_detect(sub("\\\\\\\\", "//", OutPath), 
                          paste0(SimcypDir$LgFileDir, "|", 
                                 SimcypDir$SharePtDir))){
                
                OutPath <- paste0("C:/Users/", Sys.info()[["user"]], 
                                  "/Documents")
                warning(paste0("You have attempted to save a Word file from this function on either the Large File Store or SharePoint, and Windows permissions do not allow this. We will attempt to set your working directory to your Documents folder, which we think should be ", 
                               OutPath,
                               ". Since your Documents folder is a local directory, you should be able to save Word output and then, later, copy it to the drive you originally requested."), 
                        call. = FALSE)
            }
            
            FileName <- basename(FileName)
            
            rmarkdown::render(system.file("rmarkdown/templates/multctplot/skeleton/skeleton.Rmd",
                                          package="SimcypConsultancy"), 
                              output_dir = OutPath, 
                              output_file = FileName, 
                              quiet = TRUE)
            # Note: The "system.file" part of the call means "go to where the
            # package is installed, search for the file listed, and return its
            # full path.
            
        } else {
            # This is when they want any kind of graphical file format.
            ggsave(FileName, height = fig_height, width = fig_width, dpi = 600, 
                   plot = Out)
            
        }
    }
    
    return(Out)
    
}
