#' Get information from an Excel report-input file about a section for a report
#'
#' \code{getSectionInfo} pulls information from an Excel file generated by
#' \code{\link{generateReportInputForm}} to feed into the function
#' \code{\link{so_table}}. \strong{Most users probably do not want this function
#' alone since it's mainly for use inside other functions.} Since this requires
#' comparing observed data to a simulator output file, setting up the input for
#' this function requires a few steps:
#'
#' \enumerate{
#'
#' \item{Use the function \code{\link{generateReportInputForm}} to create an
#' Excel file where you can enter information about your project.}
#'
#' \item{Go to the tab "observed data" and enter details about your observed
#' data. It's ok if you don't have all the information; anything that's missing
#' won't be included in the final S/O table. It's also ok to rename this tab
#' and/or make copies of it within the same Excel file for making other S/O
#' tables.}
#'
#' \item{Go to the tab "table and graph input" and fill out information here for
#' the specific report section you're making this S/O table for. Make sure that
#' whatever you list as the tab that contains information about the observed
#' data is exactly the same as the actual tab name that you filled out in step
#' 2. Also make sure that the file names include the full file path.}
#'
#' \item{Save your Excel file.}
#'
#' \item{Here, within RStudio (or within the shiny app that we plan to make!),
#' run this function using the name of that Excel file as input for
#' \code{report_input_file} and the name of the "table and graph input" tab as
#' the input for \code{sheet}. Note: If the Excel file lives on SharePoint,
#' you'll need to close it or this function will just keep running and not
#' generate any output while it waits for access to the file.} }
#'
#' @param report_input_file the name of the Excel file created by running
#'   \code{\link{generateReportInputForm}}, including the path if it's in any
#'   other directory than the current one, which you have now filled out
#' @param sheet the sheet in the Excel file that contains information about this
#'   section of the report. In the original template, this was the tab titled
#'   "table and graph input".
#'
#' @return a list object
#' @export
#'
#' @examples
#' # getSectionInfo(report_input_file = "//certara.com/data/sites/SHF/Consult/abc-1a/Report input.xlsx")
#' 
getSectionInfo <- function(report_input_file = NA,
                           sheet = "table and graph input"){
    
    # If they didn't include ".xlsx" at the end, add that.
    report_input_file <- ifelse(str_detect(report_input_file, "xlsx$"), 
                                report_input_file, paste0(report_input_file, ".xlsx"))
    
    # if("data.frame" %in% class(section_input_DF)){# RETURN TO THIS AND ADJUST FOR SITUATIONS WHEN ONLY INCLUDING DF. Need to decide how to determine whether DDI involved.
    #       InputXL <- section_input_DF
    # } else {
    InputXL <- suppressMessages(
        readxl::read_excel(path = report_input_file,
                           sheet = sheet, skip = 3))
    # }
    
    # Making each of the items in InputXL its own named item in a list so that
    # output from getSectionInfo will be exclusively a list rather than a list
    # that contains a data.frame, since the latter is annoying to code
    # namewise.
    sectionInfo <- InputXL %>% select(-Item) %>%
        mutate(Value = gsub("\\\\", "/", Value),
               Value = sub("(https://)?s08sharepoint.certara.com/sites/consult/",
                           SimcypDir$SharePtDir, Value)) %>%
        pivot_wider(names_from = RName, values_from = Value) %>%
        as.list()
    
    Deets <- extractExpDetails(sim_data_file = sectionInfo$SimFile)
    
    # Checking whether DDI involved.
    DDI <- any(complete.cases(c(Deets$Inhibitor1, Deets$Inhibitor2)))    
    
    ClinXL <- suppressMessages(
        readxl::read_excel(path = report_input_file,
                           sheet = sectionInfo$ClinStudyTab,
                           col_types = "text",
                           skip = 3))
    
    if(DDI){
        
        StartPK <- which(str_detect(ClinXL[, 1] %>% pull(1),
                                    "^Victim PK data"))
        # StartRatio <- which(str_detect(ClinXL[, 1] %>% pull(1),
        #                                "^Mean ratios of PK"))
        
        ClinXL_main <- ClinXL[1:StartPK, 1:3]
        ClinXL_vic <- ClinXL[StartPK:nrow(ClinXL), 1:3]
        ClinXL_perp <- ClinXL[StartPK:nrow(ClinXL), 4:6]
        names(ClinXL_main) <- c("Item", "RName", "Value")
        names(ClinXL_vic) <- c("Item", "RName", "Value")
        names(ClinXL_perp) <- c("Item", "RName", "Value")
        # names(ClinXL_rat) <- c("Item", "RName", "Value")
        
        # Adjusting to deal w/multiple scenarios
        DDIScenario <- unique(ClinXL_main$RName[
            which(str_detect(ClinXL_main$RName, "Scenario") &
                      complete.cases(ClinXL_main$Value))])
        DDIScenario_pretty <- switch(DDIScenario,
                                     "ScenarioA" = "SD victim, SD perpetrator",
                                     "ScenarioB" = "MD victim, SD perpetrator",
                                     "ScenarioC" = "SD victim, MD perpetrator",
                                     "ScenarioD" = "MD victim, MD perpetrator")
        Suffix <- switch(DDIScenario,
                         "ScenarioA" = "_dose1",
                         "ScenarioB" = "_ss",
                         "ScenarioC" = "_dose1",
                         "ScenarioD" = "_ss")
        
        ClinXL_vic$RName <- paste0(ClinXL_vic$RName, Suffix)
        ClinXL_perp$RName <- paste0(ClinXL_perp$RName, Suffix, "_withEffector")
        ClinXL_main <- ClinXL_main %>%
            mutate(RName = ifelse(str_detect(RName, "Scenario"),
                                  "DDIScenario", RName),
                   Value = ifelse(RName == "DDIScenario", DDIScenario_pretty, Value))
        
        ClinXL <- bind_rows(ClinXL_main, ClinXL_vic, ClinXL_perp) %>%
            filter(!str_detect(RName, "^blank")) %>%
            mutate(RName = sub("_CV_ss", "_ss_CV", RName),
                   RName = sub("_CV_dose1", "_dose1_CV", RName),
                   RName = ifelse(str_detect(RName, "_CV_"),
                                  paste0(RName, "_CV"), RName),
                   RName = sub("_CV_", "_", RName))
    }
    
    sectionInfo <- c(
        sectionInfo,
        ClinXL %>% select(-Item)  %>% unique() %>%
            pivot_wider(names_from = RName, values_from = Value) %>%
            mutate(across(.cols = -any_of(
                c("ClinStudy", "MeanType", "Tissue", "DDIRole",
                  "DDIScenario", "GMR_mean_type")),
                .fns = as.numeric)) %>%
            as.list())
    
    # Tidying up the names used for populations so that they look nice in report
    Population <- tidyPop(Deets$Population)
    NumSimSubj <- Deets[["NumSubjTrial"]] * Deets[["NumTrials"]]
    DoseFreq <- switch(as.character(Deets[["DoseInt_sub"]]),
                       "12" = "BID",
                       "24" = "QD",
                       "8" = "TID",
                       "Single Dose" = "single dose")
    Deets[["Inhibitor1"]] <- tolower(gsub(
        "SV-|Sim-|_EC|_SR|-MD|-SD|-[1-9]00 mg [QMSTBI]{1,2}D|_Fasted Soln|_Fed Capsule",
        "",
        Deets[["Inhibitor1"]]))
    Deets[["Inhibitor2"]] <- tolower(gsub(
        "SV-|Sim-|_EC|_SR|-MD|-SD|-[1-9]00 mg [QMSTBI]{1,2}D|_Fasted Soln|_Fed Capsule",
        "",
        Deets[["Inhibitor2"]]))
    DoseFreq_inhib <- switch(as.character(Deets[["DoseInt_inhib"]]),
                             "12" = "BID",
                             "24" = "QD",
                             "8" = "TID",
                             "Single Dose" = "single dose", 
                             "custom dosing" = "custom dosing")
    
    # Day substrate was administered
    StartDoseDay_sub <-
        as.numeric(sub("Day ", "",
                       str_split(Deets[["StartDayTime_sub"]], ", ")[[1]][1]))
    
    # Days inhibitor was administered
    StartDoseDay_inhib <- as.numeric(sub("Day ", "",
                                         str_split(Deets[["StartDayTime_inhib"]], ", ")[[1]][1]))
    
    LastDoseDay_inhib <-
        (Deets[["DoseInt_inhib"]] * Deets[["NumDoses_inhib"]])/24
    
    
    # Putting everything together
    sectionInfo <- c(sectionInfo, Deets, Population,
                     "NumSimSubj" = NumSimSubj,
                     "DoseFreq" = DoseFreq,
                     "DoseFreq_inhib" = DoseFreq_inhib,
                     "StartDoseDay_sub" = StartDoseDay_sub,
                     "StartDoseDay_inhib" = StartDoseDay_inhib,
                     "LastDoseDay_inhib" = LastDoseDay_inhib)
    
    sectionInfo <- sectionInfo[sort(names(sectionInfo))]
    
    return(sectionInfo)
}
