#' Get information from an Excel report-input file about a section for a report
#'
#' \code{getSectionInfo} pulls information from an Excel file generated by
#' \code{\link{generateReportInputForm}} to feed into the function
#' \code{\link{so_table}}. \strong{Most users probably do not want this function
#' alone since it's mainly for use inside other functions.} Please see
#' \code{\link{so_table}} for details.
#'
#' @param report_input_file the name of the Excel file created by running
#'   \code{\link{generateReportInputForm}}, including the path if it's in any
#'   other directory than the current one, which you have now filled out
#' @param sheet_report the sheet in the Excel report template file that contains
#'   information about this section of the report. In the original template,
#'   this was the tab titled "table and graph input".
#'
#' @return a list object
#' @export
#'
#' @examples
#' # getSectionInfo(report_input_file = "//certara.com/data/sites/SHF/Consult/abc-1a/Report input.xlsx")
#' 
getSectionInfo <- function(report_input_file = NA,
                           sheet_report = "study info - no DDI"){
    
    # If they didn't include ".xlsx" at the end, add that.
    report_input_file <- ifelse(str_detect(report_input_file, "xlsx$"), 
                                report_input_file, paste0(report_input_file, ".xlsx"))
    
    InputXL <- suppressMessages(
        readxl::read_excel(path = report_input_file,
                           sheet = sheet_report, skip = 3)) %>% 
        filter(complete.cases(RName))
    names(InputXL)[1] <- "Item"
    names(InputXL)[3] <- "Value"
    
    sim_data_file <- InputXL$Value[InputXL$RName == "SimFile"]
    if(dirname(sim_data_file) == "."){
        sim_data_file <- paste0(dirname(report_input_file), "/", sim_data_file)
    }
    
    Deets <- extractExpDetails(sim_data_file = sim_data_file)
    
    # Checking whether DDI involved.
    DDI <- any(complete.cases(c(Deets$Inhibitor1, Deets$Inhibitor2)))    
    
    if(DDI){
        
        if(any(str_detect(InputXL$Item, "Mean ratios"), na.rm = TRUE) == FALSE){
            stop("You have filled out the report input form tab for a study with no DDI, but Inhibitor 1 and/or Inhibitor 2 are present in your simulation. Please fill out the tab for studies with DDIs.")
        }
        
        ObsData <- InputXL[1:(which(str_detect(InputXL$Item, "^Simulated data")) -1),
                               c("RName", "Value")] %>% 
            bind_rows(InputXL[, 5:6] %>% 
                          rename(RName = matches("RName"),
                                 Value = matches("Value")) %>% 
                          filter(complete.cases(RName)) %>% 
                          mutate(Value = as.character(Value))) %>% 
            filter(RName != "blank") %>% 
            pivot_wider(names_from = RName, values_from = Value) %>% 
            mutate(across(.cols = -c(ClinStudy, Tissue, MeanType, GMR_mean_type),
                          .fns = as.numeric)) %>% 
            as.list()
        
    } else {
        
        if(any(str_detect(InputXL$Item, "Mean ratios"), na.rm = TRUE)){
            stop("You have filled out the report input form tab for a DDI study, but no effector compounds are present in your simulation. Please fill out the tab for studies with no DDIs.")
        }
        
        ObsData <- InputXL[1:(which(str_detect(InputXL$Item, "^Simulated data")) -1), ] %>%
            select(-Item) %>%
            filter(RName != "blank") %>%
            pivot_wider(names_from = RName, values_from = Value) %>% 
            mutate(across(.cols = -c(ClinStudy, Tissue, MeanType), .fns = as.numeric)) %>% 
            as.list()
        
    }
    
    # Tidying up the names used for populations so that they look nice in report
    Population <- tidyPop(Deets$Population)
    NumSimSubj <- Deets[["NumSubjTrial"]] * Deets[["NumTrials"]]
    DoseFreq <- switch(as.character(Deets[["DoseInt_sub"]]),
                       "12" = "BID",
                       "24" = "QD",
                       "8" = "TID",
                       "Single Dose" = "single dose", 
                       "custom dosing" = "custom dosing")
    Deets[["Inhibitor1"]] <- tolower(gsub(
        "SV-|Sim-|_EC|_SR|-MD|-SD|_FO|-[1-9]00 mg [QMSTBI]{1,2}D|_Fasted Soln|_Fed Capsule",
        "",
        Deets[["Inhibitor1"]]))
    Deets[["Inhibitor2"]] <- tolower(gsub(
        "SV-|Sim-|_EC|_SR|-MD|-SD|_FO|-[1-9]00 mg [QMSTBI]{1,2}D|_Fasted Soln|_Fed Capsule",
        "",
        Deets[["Inhibitor2"]]))
    DoseFreq_inhib <- switch(as.character(Deets[["DoseInt_inhib"]]),
                             "12" = "BID",
                             "24" = "QD",
                             "8" = "TID",
                             "Single Dose" = "single dose", 
                             "custom dosing" = "custom dosing")
    
    # Day substrate was administered
    StartDoseDay_sub <-
        as.numeric(sub("Day ", "",
                       str_split(Deets[["StartDayTime_sub"]], ", ")[[1]][1]))
    
    # Days inhibitor was administered
    StartDoseDay_inhib <- as.numeric(sub("Day ", "",
                                         str_split(Deets[["StartDayTime_inhib"]], ", ")[[1]][1]))
    
    LastDoseDay_inhib <-
        (Deets[["DoseInt_inhib"]] * Deets[["NumDoses_inhib"]])/24
    
    
    # Putting everything together
    sectionInfo <- c(Deets, Population,
                     "sim_data_file" = sim_data_file,
                     "NumSimSubj" = NumSimSubj,
                     "DoseFreq" = DoseFreq,
                     "DoseFreq_inhib" = DoseFreq_inhib,
                     "StartDoseDay_sub" = StartDoseDay_sub,
                     "StartDoseDay_inhib" = StartDoseDay_inhib,
                     "LastDoseDay_inhib" = LastDoseDay_inhib)
    
    sectionInfo[["ObsData"]] <- ObsData[sapply(ObsData, complete.cases)]
    
    sectionInfo <- sectionInfo[sort(names(sectionInfo))]
    
    return(sectionInfo)
}
