#' Make simulated vs. observed tables for reports
#'
#' \code{so_table} creates simulated vs. observed tables for reports and
#' presentations, including reporting means, CVs, confidence intervals or
#' percentiles, and ratios of simulated vs. observed mean values. The data it
#' uses for these calculations are standard information about the observed and
#' simulated data in the format generated by running
#' \code{\link{getSectionInfo}}.
#'
#' @param Info information about the simulated and observed data. This is output
#'   from the function \code{\link{getSectionInfo}} or the name of the Excel
#'   file to be piped to \code{\link{getSectionInfo}}.
#' @param sheet the sheet name to read if "Info" is not the output from
#'   \code{getSectionInfo} but the name of an Excel file
#' @param mean_type Arithmetic or geometric means? Only specify this if you'd
#'   like to override the value listed in "Info". If no value is specified here
#'   or in "Info", the default is "geometric".
#' @param variability_option  What type of variability would you like the table
#'   to include? Options are: "90\% CI", "95\% CI", "95th percentiles", or any
#'   combination of those, e.g. \code{variability_option = c("90\% CI", "95th
#'   percentiles"). The arithmetic CV will automatically be included.}
#' @param concatVariability Would you like to have the variability concatenated?
#'   TRUE or FALSE. If "TRUE", the output will be formatted into a single row
#'   and listed as the lower confidence interval or percentile to the upper CI
#'   or percentile. Ex: "2400 to 2700"
#' @param includeT12 TRUE or FALSE on whether to include t1/2 as a parameter in
#'   the output table
#' @return a data.frame
#' @export
#' @examples
#' # No examples yet.


so_table <- function(Info, sheet = NA,
                     mean_type = NA,
                     variability_option = "90% CI",
                     concatVariability = FALSE,
                     includeT12 = FALSE){

      if(class(Info) != "list"){
            Info <- getSectionInfo(Info, sheet = sheet)
      }

      D1 <- c("AUCinf", "CL", "Cmax", "HalfLife", "tmax")
      D2 <- sub("AUCinf", "AUCtau", D1)

      D1 <- paste0(D1, "_dose1")
      D2 <- paste0(D2, "_ss")

      Dcomp <- c("AUCinf_ratio_dose1", "AUCtau_ratio_dose1",
                 "Cmax_ratio_dose1", "Cmax_ratio_ss")

      ObsToPull <- c(D1, paste0(D1, "_withEffector"),
                     D2, paste0(D2, "_withEffector"), Dcomp)

      PKToPull <- ObsToPull[!str_detect(ObsToPull, "_CV")]

      EffectorPresent <- complete.cases(Info$Deets$Inhibitor)
      DoseRegimen <- Info$Deets$Regimen_sub

      # Getting PK parameters from the AUC tab
      MyPKParam <- switch(
            paste(DoseRegimen, EffectorPresent),
            "Single Dose FALSE" = PKToPull[
                  str_detect(PKToPull, "dose1") &
                        !str_detect(PKToPull, "withEffector")],
            "Single Dose TRUE" = PKToPull[
                  str_detect(PKToPull, "dose1")],
            "Multiple Dose FALSE" = PKToPull[!str_detect(PKToPull, "withEffector")],
            "Multiple Dose TRUE" = PKToPull)

      MyPKResults <- extractPK(Info$SimFile,
                           PKparameters = MyPKParam,
                           returnAggregateOrIndiv = "aggregate")

      MeanType <- ifelse(is.na(mean_type),
                         Info$MeanType,
                         mean_type)
      MeanType <- ifelse(is.na(MeanType), "geometric", MeanType)

      VarOpt1 <- variability_option[1]
      VariabilityNames <- switch(VarOpt1,
                                "90% CI" = c("CI_10", "CI_90"),
                                "95% CI" = c("CI_05", "CI_95"),
                                "95th percentiles" = c("Q5th", "Q95th"))

      MyPKResults <- MyPKResults %>%
            filter(!Statistic == ifelse(MeanType == "geometric",
                                        "Mean", "Geometric Mean")) %>%
            mutate(Stat = recode(Statistic,
                                 "Mean" = "GMean",
                                 "Geometric Mean" = "GMean",
                                 "90% confidence interval around the geometric mean(lower limit)" = "CI_10",
                                 "90% confidence interval around the geometric mean(upper limit)" = "CI_90",
                                 "95% confidence interval around the geometric mean(lower limit)" = "CI_05",
                                 "95% confidence interval around the geometric mean(upper limit)" = "CI_95",
                                 "5th centile" = "Q5th",
                                 "95th centile" = "Q95th",
                                 "cv" = "CV",
                                 "Std Dev" = "SD")) %>%
            select(-Statistic)

      # Adjusting tmax values since the geometric mean row will actually be the
      # median, VariabilityNames[1] will be the min, and VariabilityNames[2] will
      # be the max.
      MyPKResults$tmax_dose1[MyPKResults$Stat == "GMean"] <-
            MyPKResults$tmax_dose1[MyPKResults$Stat == "Median"]
      MyPKResults$tmax_dose1[MyPKResults$Stat == VariabilityNames[1]] <-
            MyPKResults$tmax_dose1[MyPKResults$Stat == "Min Val"]
      MyPKResults$tmax_dose1[MyPKResults$Stat == VariabilityNames[2]] <-
            MyPKResults$tmax_dose1[MyPKResults$Stat == "Max Val"]

      # Formatting
      MyPKResults <- MyPKResults %>%
            pivot_longer(cols = -Stat, names_to = "PKParam",
                         values_to = "Value") %>%
            mutate(Value = if_else(Stat == "CV",
                                   round(Value * 100, 0),
                                   # Per Christiane: 3 sig figs for everything
                                   # or full number when > 100
                                   if_else(Value > 100,
                                           round(Value, 0), signif(Value, 3)))) %>%
            filter(Stat %in% c("GMean", "CI_10", "CI_90", "CI_05", "CI_95",
                               "Q5th", "Q95th", "CV")) %>%
            pivot_wider(names_from = PKParam, values_from = Value)

      # Observed data. Not included when section is model application.
      if(Info$InputXL$Value[which(Info$InputXL$RName == "ModelPurpose")] !=
         "application"){

            MyObsPKParam <- c(MyPKParam, paste0(MyPKParam, "_CV"))
            if(EffectorPresent){
                  MyObsPKParam <- c(MyObsPKParam,
                                    "Cmax_ratio_ss_90CIL", "Cmax_ratio_ss_90CIU",
                                    "AUCtau_ratio_ss_90CIL", "AUCtau_ratio_ss_90CIU")
            }

            MyObsPK <- Info$ClinXL %>%
                  filter(RName %in% MyObsPKParam) %>%
                  select(RName, Value) %>%
                  mutate(Value = as.numeric(Value),
                         Value = ifelse(str_detect(RName, "CV"),
                                        round(Value * 100, 0), signif(Value, 3)),
                         Stat = ifelse(str_detect(RName, "CV"), "CV_obs", "GMean"),
                         Stat = ifelse(str_detect(RName, "CIU"), "CIU_obs", Stat),
                         Stat = ifelse(str_detect(RName, "CIL"), "CIL_obs", Stat),
                         RName = sub("_CV|_[0-9]{2}CI[UL]", "", RName)) %>%
                  pivot_wider(names_from = RName, values_from = Value)

            # Only want to keep the columns where there are values for the observed
            # mean data.
            MyObsPK <- MyObsPK %>% select(where(function(x) complete.cases(x[1])))

            # Calculating S/O
            GMeans <- MyPKResults %>% filter(Stat == "GMean") %>%
                  pivot_longer(names_to = "PKParam_short", values_to = "Sim",
                               cols = -Stat) %>%
                  left_join(MyObsPK %>% filter(Stat == "GMean") %>%
                                  pivot_longer(names_to = "PKParam_short", values_to = "Obs",
                                               cols = -Stat)) %>%
                  mutate(S_O = round(Sim / Obs, 2)) %>%
                  select(PKParam_short, S_O) %>%
                  pivot_wider(names_from = PKParam_short, values_from = S_O) %>%
                  mutate(Stat = "S/O")

            # Next, selecting only the appropriate columns for table, making
            # everything character, and adding % symbols to CV rows
            MyPKResults <- MyPKResults %>%
                  bind_rows(MyObsPK %>% mutate(Stat = ifelse(Stat == "GMean",
                                                             "GMean_obs", Stat))) %>%
                  bind_rows(GMeans)

            MyPKResults <- MyPKResults[, names(MyObsPK)]

      }

      MyPKResults <- MyPKResults %>%
            mutate_all(.funs = as.character) %>%
            mutate(across(.cols = !Stat,
                          .fns = function(x) ifelse(str_detect(Stat, "CV"),
                                                    paste0(x, "%"), x)),
                   across(.cols = everything(),
                          .fns = function(x) ifelse(x == "NA%", NA, x)))
      # If this throws an error for you, try running "tidyverse_update()", copy
      # whatever it says is out of date, restart your R session (Ctrl Shift
      # F10), and then paste the output (something like
      # "install.packages(c("dbplyr", "dplyr", "dtplyr", ... ") and execute.

      if(EffectorPresent){
            # Only want AUC, Cmax, GMR w/ and w/out effector
            MyPKResults <- MyPKResults %>%
                  select(Stat, matches("AUC|Cmax|GMR"))

            PKToPull <-  c(PKToPull,
                           "AUCinf_ratio_dose1", "Cmax_ratio_dose1",
                           "AUCtau_ratio_ss", "Cmax_ratio_ss")

      }

      # Talked w/Christiane about including t1/2 since that's included in the table,
      # and she said that Massoud prefers to NOT include it b/c there can be glitches
      # with its calculation. It's only included if there's a specific reason the
      # client wants it. Optionally including it.
      if(includeT12 == FALSE){
            MyPKResults <- MyPKResults %>% select(-matches("HalfLife"))
      }

      # Filtering rows as requested by user
      VarOpts_tableRows <- list("90% CI" = c("CI_10", "CI_90"),
                                "95% CI" = c("CI_05", "CI_95"),
                                "95th percentiles" = c("Q5th", "Q95th"))
      VarOptsNotChosen <- setdiff(c("90% CI", "95% CI", "95th percentiles"),
                                  variability_option)

      if(length(VarOptsNotChosen) > 0){
            MyPKResults <- MyPKResults %>%
                  filter(!Stat %in% unlist(VarOpts_tableRows[VarOptsNotChosen]))
      }

      # Concatenating the rows w/lower and upper limits of variability when
      # requested
      if(concatVariability){

            # Note: When multiple options are chosen for variability type,
            # concatVariability doesn't work. Will need to fix this later.
            VarRows <- VarOpts_tableRows[variability_option]
            VarRows[["obs"]] <- c("CIL_obs", "CIU_obs")
            for(j in names(VarRows)){
                  temp <- MyPKResults %>%
                        filter(Stat %in% as.character(unlist(VarRows[[j]]))) %>%
                        mutate(across(.cols = !matches("Stat"),
                                      .fns = function(x) {
                                            ifelse(all(complete.cases(c(x[1], x[2]))),
                                                   paste(x[1], "to", x[2]), NA)}),
                               Stat = switch(j,
                                             "90% CI" = "CI90concat",
                                             "95% CI" = "CI95concat",
                                             "95th percentile" = "Q95thconcat",
                                             "obs" = "CIobsconcat"))

                  MyPKResults[which(MyPKResults$Stat == VarRows[[j]][1]), ] <-
                        temp[1, ]
                  MyPKResults <- MyPKResults %>% filter(Stat != VarRows[[j]][2])
                  rm(temp)
            }
      }

      # Renaming statistics to match what's in template
      StatNames <- c("GMean" = "Simulated",
                     "CV" = "CV%",
                     "CI_10" = "90% CI - Lower",
                     "CI_90" = "90% CI - Upper",
                     "CI90concat" = "90% CI",
                     "CI_05" = "95% CI - Lower",
                     "CI_95" = "95% CI - Upper",
                     "CI95concat" = "95% CI",
                     "Q5th" = "5th Percentile",
                     "Q95th" = "95th Percentile",
                     "Q95thconcat" = "5th to 95th Percentile",
                     "GMean_obs" = "Observed",
                     "CV_obs" = "CV%",
                     "CIL_obs" = "observed CI - Lower",
                     "CIU_obs" = "observed CI - Upper",
                     "CIobsconcat" = "Observed CI",
                     "S/O" = "S/O")

      MyPKResults <- MyPKResults %>%
            mutate(Statistic = as.character(Stat),
                   Statistic = StatNames[Statistic]) %>%
            select(-Stat) %>%
            select(Statistic, everything())

      # Getting columns in a good order
      MyPKResults <- MyPKResults %>%
            select(any_of(c("Statistic", PKToPull)))

      # Adding final column names
      PKToPull_pretty <-
            sapply(PKToPull,
                   FUN = function(x) ifelse(str_detect(x, "_dose1"),
                                            paste("Dose 1", sub("_dose1", "", x)),
                                            paste("Steady-state", sub("_ss", "", x))))
      PKToPull_pretty <- sub("_withEffector", " with effector", PKToPull_pretty)
      PKToPull_pretty <- sub("CL", "CL/F (L/h)", PKToPull_pretty)
      PKToPull_pretty <- sub("AUCinf", "AUC0 to inf (h*ng/mL)", PKToPull_pretty)
      PKToPull_pretty <- sub("AUCtau", "AUC0 to tau (h*ng/mL)", PKToPull_pretty)
      PKToPull_pretty <- sub("Cmax", "Cmax (ng/mL)", PKToPull_pretty)
      PKToPull_pretty <- sub("HalfLife", "t1/2 (h)", PKToPull_pretty)
      PKToPull_pretty <- sub("tmax", "tmax (h)", PKToPull_pretty)
      PKToPull_pretty[str_detect(PKToPull_pretty, "with effector")] <-
            sub(" \\(", " with effector (", PKToPull_pretty[str_detect(PKToPull_pretty, "with effector")])
      PKToPull_pretty[str_detect(PKToPull_pretty, "with effector")] <-
            sub(" with effector$", "", PKToPull_pretty[str_detect(PKToPull_pretty, "with effector")])
      PKToPull_pretty <- sub("GMR_", "geometric mean ratio ", PKToPull_pretty)

      PKToPull_pretty <- c("Statistic" = "Statistic", PKToPull_pretty)

      names(MyPKResults) <- PKToPull_pretty[names(MyPKResults)]

      return(MyPKResults)
}
